name: wrap
description: >-
  Chain-style programming support to avoid nesting hell in Flutter
  with some tools to avoid material component usages.
version: 0.0.0
environment: {sdk: ^3.5.0, flutter: ">=3.24.1 <4.0.0"}

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^4.0.0
